### ISSUE TITLE
[Feature Request] rearrange games order and .txt file editor?

### ISSUE THREAD

**Issue by alfredox123** [joel16/CMFileManager-PSP#33]
could be posible to add and txt file editor and a way to rearrange games order? txt file editor would be extremely usefull, the other feature not so much but would be cool to have it though

**Comment by CDScissor** [comment]
The only usefulness I can see from the text editor is jumping from server to server and hotspot to hotspot from Pro Online Play, which is a real hassle with having to connect to a PC instead of just doing it on the PSP itself. The Game Order rearrangement seems really useful to me but that seems to be a much taller order that a text editor.

**Comment by alfredox123** [comment]
yeah, exactly for that i will be using the text editor and yeah text editor its a more important thing (for me atleast) than rearrangement of things on psp

**Comment by joel16** [comment]
There's already a homebrew that does this called "homebrew sorter". This isn't really the purpose of a file manager IMO. Also the text editor feature request already exists so I'll close this one.
